USE [master];

DROP DATABASE IF EXISTS [Banco Edge];
CREATE DATABASE [Banco Edge];

GO

USE [Banco Edge];
GO

CREATE TABLE [Cliente](
    [Id] INTEGER IDENTITY PRIMARY KEY NOT NULL,
    [Nome] VARCHAR(100) NOT NULL,
    [Email] VARCHAR(500) UNIQUE NOT NULL,
    [Telefone] VARCHAR(15) NOT NULL,
    [CpfOuCnpj] VARCHAR(14) UNIQUE NOT NULL,
    [Senha] VARCHAR(90) NOT NULL
);

CREATE TABLE [Login](
   [Id] INTEGER IDENTITY PRIMARY KEY NOT NULL,
   [Token] VARCHAR(90) NOT NULL,
   [IP] VARBINARY(4) NOT NULL,
   [ContaId] INTEGER NOT NULL,
   FOREIGN KEY ([ContaId]) REFERENCES [Cliente]([Id])
);

CREATE TABLE [Conta](
    [Id] INTEGER IDENTITY PRIMARY KEY NOT NULL,
    [Dono] INTEGER NOT NULL,
    [Saldo] MONEY NULL DEFAULT 0.0,
    [Tipo] TINYINT NOT NULL DEFAULT 1,
    [Criacao] DATETIME2 NOT NULL,
    FOREIGN KEY ([Dono]) REFERENCES [Cliente]([ID])
);