USE [master];

DROP DATABASE IF EXISTS [Banco Edge];
CREATE DATABASE [Banco Edge]
GO

USE [Banco Edge];
GO

CREATE TABLE [Cliente](
[Id] INTEGER IDENTITY PRIMARY KEY NOT NULL,
[Nome] VARCHAR(100) NOT NULL,
[Email] VARCHAR(500) UNIQUE NOT NULL,
[CpfCnpj] VARCHAR(14) NOT NULL
);

CREATE TABLE [Conta](
[Id] INTEGER IDENTITY PRIMARY KEY NOT NULL,
[Dono] INTEGER NOT NULL,
[Saldo] MONEY NULL DEFAULT 0.0,
[Criacao] DATETIME2 NOT NULL,
FOREIGN KEY ([Dono]) REFERENCES [Cliente]([ID])
)